### ISSUE TITLE
Switch_Case

### ISSUE THREAD

**Issue by farzadafi** [HoseinRezaeeM/Hossein_Rezaei_HW07_Maktab101#1]
Hi Hosein, I saw you're use from Switch_case in Menu class, but switch case in Java 17 is better written with an arrow(->), if you are writing with this approach, you don't have to write break, break, break, break :), and this is very cleaner approach, and pay attention if you are want to write just one line:
`case 1 -> print("farzad")`
but if you want to write more than one line in your case:
`case 2 -> {
    print("farzad");
    print("hosein");
}`

Your future self is watching you right now  :) smile my friend

**Comment by HoseinRezaeeM** [comment]
Thanks Mr.Afshar ,very Good

**Comment by farzadafi** [comment]
:), I close this issue
