### ISSUE TITLE
maven dependency

### ISSUE THREAD

**Issue by HoseinRezaeeM** [HoseinRezaeeM/Hossein_Rezaei_HW07_Maktab101#3]
Hi Mr.Afshar
We can create jar file by Excute maven Goal in Maven
write maven clean install and press enter my project jar file created in m2
and we should copy groupId, arcifactid my project at pom to other pom project and we used dependency project
Do you agree?

@HoseinRezaeeM 
@farzadafi

**Comment by farzadafi** [comment]
Hi, my Friend, I think you do not need to enter the command `mvn clean install`, and `mvn clean package` is sufficient for this goal, but overall you are correct :)
excuse me for the latency in answers

**Comment by HoseinRezaeeM** [comment]
Thanks
